//! Raw FFI bindings to mimalloc 3.0.12, auto-generated from `mimalloc.h`.
//!
//! Compiled from the vendored mimalloc source at `../mimalloc/`.
//! Bindings are generated by `bindgen` at build time — they always match
//! the exact C header, eliminating manual drift.

#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

// Auto-generated bindings from mimalloc.h
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Ensure mimalloc is initialized. Must be called before any mimalloc API.
/// Safe to call multiple times (internally uses `mi_atomic_once`).
pub fn ensure_initialized() {
    unsafe { mi_thread_init() };
}

// ---------------------------------------------------------------------------
// GlobalAlloc implementation
// ---------------------------------------------------------------------------

use std::alloc::{GlobalAlloc, Layout};

/// mimalloc as a Rust global allocator.
///
/// ```rust
/// use bisque_mimalloc_sys::MiMalloc;
///
/// #[global_allocator]
/// static GLOBAL: MiMalloc = MiMalloc;
/// ```
pub struct MiMalloc;

unsafe impl GlobalAlloc for MiMalloc {
    #[inline]
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        unsafe { mi_malloc_aligned(layout.size(), layout.align()) as *mut u8 }
        // unsafe { mi_malloc(layout.size()) as *mut u8 }
    }

    #[inline]
    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        unsafe { mi_zalloc_aligned(layout.size(), layout.align()) as *mut u8 }
    }

    #[inline]
    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        unsafe { mi_free(ptr as *mut core::ffi::c_void) }
    }

    #[inline]
    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        unsafe {
            mi_realloc_aligned(ptr as *mut core::ffi::c_void, new_size, layout.align()) as *mut u8
        }
    }
}

// Ensure Send+Sync for the global allocator marker type.
unsafe impl Send for MiMalloc {}
unsafe impl Sync for MiMalloc {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_thread_malloc_free() {
        let t = std::thread::spawn(|| {
            ensure_initialized();
            let p = unsafe { mi_malloc(256) };
            assert!(!p.is_null());
            unsafe { mi_free(p) };
        });
        t.join().unwrap();
    }

    #[test]
    fn test_exclusive_heap_create() {
        let t = std::thread::spawn(|| {
            ensure_initialized();
            // MI_SEGMENT_SIZE = 32 MiB on 64-bit, need at least 2 blocks = 64 MiB
            let size: usize = 128 * 1024 * 1024;
            let align: usize = 32 * 1024 * 1024; // MI_SEGMENT_ALIGN
            let mem = unsafe { mi_malloc_aligned(size, align) };
            assert!(!mem.is_null(), "aligned alloc failed");
            unsafe { std::ptr::write_bytes(mem as *mut u8, 0, size) };

            let heap = unsafe { _mi_exclusive_heap_create(mem, size, true, true, -1) };
            assert!(!heap.is_null(), "exclusive heap create failed");

            let p = unsafe { mi_heap_malloc_aligned(heap, 256, 8) };
            assert!(!p.is_null(), "heap alloc failed");
            unsafe { mi_free(p) };
        });
        t.join().unwrap();
    }
}
