//! Raw FFI bindings to mimalloc 3.2.8, auto-generated from `mimalloc.h`.
//!
//! Compiled from the vendored mimalloc source at `../mimalloc/`.
//! Bindings are generated by `bindgen` at build time — they always match
//! the exact C header, eliminating manual drift.

#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

// Auto-generated bindings from mimalloc.h
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

/// Ensure mimalloc is initialized. Must be called before any mimalloc API.
/// Safe to call multiple times (internally uses `mi_atomic_once`).
pub fn ensure_initialized() {
    unsafe { mi_thread_init() };
}

// ---------------------------------------------------------------------------
// GlobalAlloc implementation
// ---------------------------------------------------------------------------

use std::alloc::{GlobalAlloc, Layout};

/// mimalloc as a Rust global allocator.
///
/// ```rust
/// use bisque_mimalloc_sys::MiMalloc;
///
/// #[global_allocator]
/// static GLOBAL: MiMalloc = MiMalloc;
/// ```
pub struct MiMalloc;

unsafe impl GlobalAlloc for MiMalloc {
    #[inline]
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        unsafe { mi_malloc_aligned(layout.size(), layout.align()) as *mut u8 }
        // unsafe { mi_malloc(layout.size()) as *mut u8 }
    }

    #[inline]
    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        unsafe { mi_zalloc_aligned(layout.size(), layout.align()) as *mut u8 }
    }

    #[inline]
    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        unsafe { mi_free(ptr as *mut core::ffi::c_void) }
    }

    #[inline]
    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        unsafe {
            mi_realloc_aligned(ptr as *mut core::ffi::c_void, new_size, layout.align()) as *mut u8
        }
    }
}

// Ensure Send+Sync for the global allocator marker type.
unsafe impl Send for MiMalloc {}
unsafe impl Sync for MiMalloc {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_thread_malloc_free() {
        let t = std::thread::spawn(|| {
            ensure_initialized();
            let p = unsafe { mi_malloc(256) };
            assert!(!p.is_null());
            unsafe { mi_free(p) };
        });
        t.join().unwrap();
    }

    #[test]
    fn test_heap_new_and_destroy() {
        let t = std::thread::spawn(|| {
            ensure_initialized();
            let heap = unsafe { mi_heap_new() };
            assert!(!heap.is_null(), "mi_heap_new failed");

            let p = unsafe { mi_heap_malloc_aligned(heap, 256, 8) };
            assert!(!p.is_null(), "heap alloc failed");
            unsafe { mi_free(p) };

            unsafe { mi_heap_destroy(heap) };
        });
        t.join().unwrap();
    }

    #[test]
    fn test_heap_memlimit() {
        let t = std::thread::spawn(|| {
            ensure_initialized();
            let heap = unsafe { mi_heap_new() };
            assert!(!heap.is_null());

            // Set a memory limit.
            unsafe { mi_heap_set_memory_limit(heap, 4 * 1024 * 1024) };
            assert_eq!(unsafe { mi_heap_get_memory_limit(heap) }, 4 * 1024 * 1024);

            // Usage should start near zero.
            let usage = unsafe { mi_heap_get_memory_usage(heap) };
            assert!(usage < 1024 * 1024, "initial usage too high: {usage}");

            unsafe { mi_heap_destroy(heap) };
        });
        t.join().unwrap();
    }
}
