//! Raw FFI bindings to mimalloc 3.0.12, auto-generated from `mimalloc.h`.
//!
//! Compiled from the vendored mimalloc source at `../mimalloc/`.
//! Bindings are generated by `bindgen` at build time — they always match
//! the exact C header, eliminating manual drift.

#![allow(non_camel_case_types)]
#![allow(non_upper_case_globals)]
#![allow(non_snake_case)]
#![allow(clippy::all)]

// Auto-generated bindings from mimalloc.h
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

// ---------------------------------------------------------------------------
// GlobalAlloc implementation
// ---------------------------------------------------------------------------

use std::alloc::{GlobalAlloc, Layout};

/// mimalloc as a Rust global allocator.
///
/// ```rust
/// use bisque_mimalloc_sys::MiMalloc;
///
/// #[global_allocator]
/// static GLOBAL: MiMalloc = MiMalloc;
/// ```
pub struct MiMalloc;

unsafe impl GlobalAlloc for MiMalloc {
    #[inline]
    unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
        // unsafe { mi_malloc_aligned(layout.size(), layout.align()) as *mut u8 }
        unsafe { mi_malloc(layout.size()) as *mut u8 }
    }

    #[inline]
    unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
        unsafe { mi_zalloc_aligned(layout.size(), layout.align()) as *mut u8 }
    }

    #[inline]
    unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
        unsafe { mi_free(ptr as *mut core::ffi::c_void) }
    }

    #[inline]
    unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
        unsafe {
            mi_realloc_aligned(ptr as *mut core::ffi::c_void, new_size, layout.align()) as *mut u8
        }
    }
}

// Ensure Send+Sync for the global allocator marker type.
unsafe impl Send for MiMalloc {}
unsafe impl Sync for MiMalloc {}
